[package]
name = "components"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.5.6"
js-sys = "0.3.72"
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.72", features = ["Document", "Element", "HtmlElement", "Window", "console"] }

[lib]
crate-type = ["cdylib", "rlib"]
